Models/Employe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DepartementEmploye.Models
{
    public class Employe
    {
        [Key]
        public int Eid { get; set; }
        [Display(Name = "Nom"), Required(ErrorMessage = "*"), MaxLength(30, ErrorMessage = "Le maximum de caractères autorisé est 30")]
        public string EName { get; set; }
        [Display(Name = "Salaire"), Required(ErrorMessage = "*")]
        public double ESalary { get; set; }
        [Display(Name = "Sexe"), Required(ErrorMessage = "*")]
        public string EGender { get; set; }
        [Display(Name = "EDOB"), Required(ErrorMessage = "*")]
        public string EDOB { get; set; }
        [Display(Name = "Département"), Required(ErrorMessage = "*")]
        public int Did { get; set; }
        [ForeignKey("Did")]
        public virtual Departement Departement { get; set; }
        [Display(Name = "Date de mise à jour"), Required(ErrorMessage = "*")]
        public string UpdateDate { get; set; }
    }
}

Controllers/EmployesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DepartementEmploye.Models;
using PagedList;

namespace DepartementEmploye.Controllers
{
    public class EmployesController : Controller
    {
        private DepartementEmployeContext db = new DepartementEmployeContext();
        int pageSize = 1;
        // GET: Employes
        public ActionResult Index(int? page, int? Departement, string Nom, double? Salaire)
        {
            page = page.HasValue ? page : 1;
            ViewBag.Departements = db.departements.ToList();
            ViewBag.Departement = Departement != null ? Departement : (int?)null;
            ViewBag.Nom = !string.IsNullOrEmpty(Nom) ? Nom : string.Empty;
            ViewBag.Salaire = Salaire != null ? Salaire : (double?)null;

            var employes = db.employes.Include(e => e.Departement);
            if(Departement != null)
            {
                employes = employes.Where(a => a.Did == Departement);
            }
            if(!string.IsNullOrEmpty(Nom))
            {
                employes = employes.Where(a => a.EName.ToUpper().Contains(Nom.ToUpper()));
            }
            if(Salaire != null)
            {
                employes = employes.Where(a => a.ESalary == Salaire);
            }

            return View(employes.ToList().ToPagedList((int)page, pageSize));
        }

        // GET: Employes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = db.employes.Find(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            return View(employe);
        }

        // GET: Employes/Create
        public ActionResult Create()
        {
            ViewBag.Did = db.departements.ToList();
            ViewBag.sexePers = listgenre();
            //ViewBag.Did = new SelectList(db.departements, "Did", "DName");
            return View();
        }

        public List<SelectListItem> listgenre()
        {
            List<SelectListItem> liste = new List<SelectListItem>();
            SelectListItem l = new SelectListItem { Text = "Féminin", Value = "F" };
            liste.Add(l);
            l = new SelectListItem { Text = "Masculin", Value = "M" };
            liste.Add(l);
            
            return liste;
        }

        // POST: Employes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Eid,EName,ESalary,EGender,EDOB,Did,UpdateDate")] Employe employe)
        {
            if (ModelState.IsValid)
            {
                db.employes.Add(employe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.sexePers = listgenre();
            ViewBag.Did = db.departements.ToList();
            return View(employe);
        }

        // GET: Employes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = db.employes.Find(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            ViewBag.Did = new SelectList(db.departements, "Did", "DName", employe.Did);
            return View(employe);
        }

        // POST: Employes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Eid,EName,ESalary,EGender,EDOB,Did,UpdateDate")] Employe employe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Did = new SelectList(db.departements, "Did", "DName", employe.Did);
            return View(employe);
        }

        // GET: Employes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = db.employes.Find(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            return View(employe);
        }

        // POST: Employes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employe employe = db.employes.Find(id);
            db.employes.Remove(employe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Employes/Create.cshtml
@model DepartementEmploye.Models.Employe

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ESalary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ESalary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ESalary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EGender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("sexePers", new List<SelectListItem>{
              new SelectListItem{ Text="---Sélectionner le sexe---", Value = "" },
              new SelectListItem{ Text="Féminin", Value = "F" },
              new SelectListItem{ Text="Masculin", Value = "M" }
        }, new { @class = "form-control" })*@
                @Html.DropDownList("EGender", new SelectList(ViewBag.sexePers, "Value", "Text"), "---Selectionnez le sexe---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EGender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EDOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EDOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EDOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Did, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Did", new SelectList(ViewBag.Did, "Did", "DName"), "---Selectionnez le département---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Did, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Employes/Delete.cshtml
@model DepartementEmploye.Models.Employe

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Departement.DName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departement.DName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ESalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESalary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EGender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EGender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EDOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EDOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Employes/Details.cshtml
@model DepartementEmploye.Models.Employe

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Employe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Departement.DName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departement.DName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ESalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESalary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EGender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EGender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EDOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EDOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Eid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Employes/Edit.cshtml
@model DepartementEmploye.Models.Employe

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Eid)

        <div class="form-group">
            @Html.LabelFor(model => model.EName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ESalary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ESalary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ESalary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EGender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EGender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EGender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EDOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EDOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EDOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Did, "Did", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Did", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Did, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Employes/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<DepartementEmploye.Models.Employe>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">GESTION DES EMPLOYES</h2>

<div class="row">
    <div class="col-xs-12 col-md-12">
        <div class="widget">


            <div class="widget-body">

                @using (Html.BeginForm("Index", "Employes", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <b> Departement</b>
                                @Html.DropDownList("Departement", new SelectList(ViewBag.Departements, "Did", "DName"), "Selectionnez...", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <b> Nom</b>
                                @Html.TextBox("Nom", ViewBag.Nom as string, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <b> Salaire</b>
                                @Html.TextBox("Salaire", ViewBag.Salaire as string, new { @class = "form-control" })
                            </div>
                        </div>

                    </div>
                    <div><input type="submit" value="Rechercher" class="btn btn-primary" /></div>

                }

            </div>


        </div>

    </div>
</div>


<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">
        Nouveau
    </a>
</p>
<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Departement.DName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().EName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ESalary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().EGender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().EDOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().UpdateDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Departement.DName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ESalary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EGender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdateDate)
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id = item.Eid })" class="btn btn-warning">edit</a>
                <a href="@Url.Action("Details", new { id = item.Eid })" class="btn btn-info">voir </a>
                <a href="@Url.Action("Delete", new { id = item.Eid })" onclick="return confirm('Etes-vous sûre de vouloir supprimer cet agent ?')" class="btn btn-danger">supprimer</a>
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, Departement = ViewBag.Departement, Nom = ViewBag.Nom, Salaire = ViewBag.Salaire }))